const fs = require('fs');
const path = require('path');

const DEFAULT_OUTPUT_FILE = path.join(__dirname, '..', 'requirementMapping.js');
const FALLBACK_REQUIREMENT_NAME = 'Unmatched Requirements';

const normaliseName = (text) => {
  if (typeof text !== 'string') return '';

  return text
    .normalize('NFKC')
    .toLocaleLowerCase('en-AU')
    .trim()
    .replace(/\s+/g, ' ');
};

function validateRequirement(requirement, source, index) {
  if (!requirement || typeof requirement !== 'object') {
    throw new TypeError(`${source}[${index}] must be an object`);
  }
  if (typeof requirement.id !== 'string' || !requirement.id.trim()) {
    throw new TypeError(`${source}[${index}].id must be a non-empty string`);
  }
  if (typeof requirement.name !== 'string' || !requirement.name.trim()) {
    throw new TypeError(`${source}[${index}].name must be a non-empty string`);
  }
}

function buildRequirementMapping(namesFromCM, namesFromNP) {
  if (!Array.isArray(namesFromCM) || !Array.isArray(namesFromNP)) {
    throw new TypeError('namesFromCM and namesFromNP must both be arrays');
  }

  namesFromCM.forEach((item, index) => {
    validateRequirement(item, 'namesFromCM', index);
  });
  namesFromNP.forEach((item, index) => {
    validateRequirement(item, 'namesFromNP', index);
  });

  // Keep every new-system item under its normalised name. More than one item
  // with the same name is ambiguous, so it must not be selected silently.
  const npByName = new Map();
  for (const requirement of namesFromNP) {
    const name = normaliseName(requirement.name);
    const requirements = npByName.get(name) ?? [];
    requirements.push(requirement);
    npByName.set(name, requirements);
  }

  const fallbackRequirements = namesFromNP.filter(
    ({ name }) => name === FALLBACK_REQUIREMENT_NAME,
  );
  if (fallbackRequirements.length !== 1) {
    throw new Error(
      `NotusPoint must contain exactly one requirement named "${FALLBACK_REQUIREMENT_NAME}"`,
    );
  }
  const fallbackRequirement = fallbackRequirements[0];

  const mapping = {};
  const matches = [];
  const unmatched = [];
  const ambiguous = [];

  for (const oldRequirement of namesFromCM) {
    const candidates = npByName.get(normaliseName(oldRequirement.name)) ?? [];

    if (candidates.length === 0) {
      unmatched.push(oldRequirement);
    } else if (candidates.length > 1) {
      ambiguous.push({ oldRequirement, candidates });
    }

    // Anything without one unique name match is deliberately sent to the
    // configured catch-all requirement instead of being left unmapped.
    const newRequirement = candidates.length === 1
      ? candidates[0]
      : fallbackRequirement;
    const existingNewId = mapping[oldRequirement.id];
    if (existingNewId && existingNewId !== newRequirement.id) {
      throw new Error(
        `Old requirement id ${oldRequirement.id} matched more than one new id`,
      );
    }

    mapping[oldRequirement.id] = newRequirement.id;
    matches.push({ oldRequirement, newRequirement });
  }

  Object.defineProperty(mapping, 'UNMATCHED_REQUIREMENT_ID', {
    value: fallbackRequirement.id,
  });

  return { mapping, matches, unmatched, ambiguous, fallbackRequirement };
}

function oneLine(text) {
  return text.replace(/[\r\n\u2028\u2029]+/g, ' ').replace(/\s+/g, ' ').trim();
}

function renderMappingFile(result) {
  const lines = [
    '// Generated by utils/matchRequirement.js. Do not edit by hand.',
    'const requirementMapping = {',
  ];

  for (const { oldRequirement, newRequirement } of result.matches) {
    const description = `"${oneLine(oldRequirement.name)}" in CaseManager becomes "${oneLine(newRequirement.name)}" in NotusPoint`;
    lines.push(
      `  ${JSON.stringify(oldRequirement.id)}: ${JSON.stringify(newRequirement.id)}, // ${description}`,
    );
  }

  lines.push(
    '};',
    '',
    '// Used when a CM case has no Referral Type selected.',
    `Object.defineProperty(requirementMapping, 'UNMATCHED_REQUIREMENT_ID', { value: ${JSON.stringify(result.fallbackRequirement.id)} });`,
    '',
    'module.exports = requirementMapping;',
    '',
  );

  if (result.ambiguous.length > 0) {
    lines.push(`// Ambiguous old requirements assigned to ${FALLBACK_REQUIREMENT_NAME}:`);
    for (const { oldRequirement, candidates } of result.ambiguous) {
      const ids = candidates.map(({ id }) => oneLine(id)).join(', ');
      lines.push(`// ${oneLine(oldRequirement.name)} (${oneLine(oldRequirement.id)}): ${ids}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function writeRequirementMappingFile(result, outputFile = DEFAULT_OUTPUT_FILE) {
  const resolvedOutputFile = path.resolve(outputFile);
  fs.mkdirSync(path.dirname(resolvedOutputFile), { recursive: true });

  // Write then rename so an interrupted run cannot leave a partial mapping.
  const temporaryFile = `${resolvedOutputFile}.tmp-${process.pid}`;
  fs.writeFileSync(temporaryFile, renderMappingFile(result), 'utf8');
  fs.renameSync(temporaryFile, resolvedOutputFile);

  return resolvedOutputFile;
}

function resolveRequirementId(requirementMapping, caseRecord) {
  const referralTypeId = caseRecord.referralTypeId;
  if (!referralTypeId) {
    const unmatchedRequirementId =
      requirementMapping.UNMATCHED_REQUIREMENT_ID;
    if (unmatchedRequirementId) return unmatchedRequirementId;
    throw new Error(`Case ${caseRecord.caseId} has no Case Manager Referral Type ID and the mapping has no Unmatched Requirements fallback`);
  }

  const requirementId = requirementMapping[referralTypeId];
  if (!requirementId) {
    throw new Error(
      `Case ${caseRecord.caseId} Referral Type ${referralTypeId} is missing from requirementMapping.js; regenerate the mapping`,
    );
  }

  return requirementId;
}

// Names are { name: string, id: string } for both systems. This returns the
// old-id -> new-id object and writes the same mapping to a CommonJS file.
function matchRequirement(namesFromCM, namesFromNP, outputFile = DEFAULT_OUTPUT_FILE) {
  const result = buildRequirementMapping(namesFromCM, namesFromNP);
  writeRequirementMappingFile(result, outputFile);
  return result.mapping;
}

module.exports = {
  DEFAULT_OUTPUT_FILE,
  FALLBACK_REQUIREMENT_NAME,
  normaliseName,
  buildRequirementMapping,
  renderMappingFile,
  writeRequirementMappingFile,
  resolveRequirementId,
  matchRequirement,
};
