// Generated by utils/matchRequirement.js. Do not edit by hand.
// Matched: 272
// Unmatched: 218
const requirementMapping = {
  "00000000-0000-0000-0000-000000000000": null, // "----------" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7c657f99-91a0-49db-a741-71a9c8418677": null, // "Activities of Daily Living Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4e82e544-bb78-497b-93c7-25ca6da4b246": null, // "Adjustment to Injury Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1314664c-9e01-4d3f-8b3f-6fac7e79941b": "3a173e4e-2e9f-48f1-b150-0acbb7eba3cb", // "Admin" in CaseManager becomes "Admin" in NotusPoint
  "9aaedb61-df6a-487b-9a88-744e516d37e4": null, // "AIA File Review" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "282b98fe-7d00-4de2-bb85-0041f9f08f3a": null, // "Analysis Only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d1be275f-a43c-402d-95ba-a65c39198a60": null, // "ass" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c37dc60c-cee6-4abf-b03f-b08ac9bc18bd": null, // "Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "af511dd9-6e89-4f15-98d7-b35fd0c8815f": null, // "assessment only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "0e5d633f-fdc2-4258-ba9d-eb22d5e69c26": null, // "Assessment Only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "98c27c82-8af2-4426-975d-ce6896b8f9d0": null, // "assessment only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c4b68b8a-5b88-4507-a4bc-b3669f5511b6": null, // "Assq" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3bb355b9-2587-48b1-aac3-595adbd44f74": null, // "Ax/follow up" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ad078367-12e8-433e-8240-faf15381d691": null, // "Ax/Training/ Mgmnt" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c879e346-2c12-45c4-88e7-b156596c3a61": null, // "Brief Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2b9626a9-6c06-4043-a35c-97859dafefc0": null, // "Building work capacity" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "912f6c04-aea5-4926-b362-afa1c8ecde60": null, // "Business Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "0983f5a3-9da5-44de-a6e9-cb03ebb47cd9": null, // "Business Gap Analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "113e415c-14e7-4db8-8431-55fa81bbaf18": null, // "Business Gap Analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7211d203-1fca-434d-a7dd-1e341f9a95f3": null, // "Business Mentoring" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8ff7322f-735c-492e-9749-0af8a79d1aa9": null, // "Business Mentoring" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5acc6dee-891a-41c4-80c8-fc3e8138b5dc": null, // "Care Needs Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "18431e46-7702-4eb5-8e34-096b8859f863": null, // "Career Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6825f53a-2a94-4b69-984a-bb65af2ac6c3": "c1a3866f-e9df-420b-b7ee-7878465530ea", // "Case Conference" in CaseManager becomes "NSW WC Medical Case Conference" in NotusPoint (fuzzy match 84%)
  "27504741-c71f-403c-b6c2-be616920486e": "c1a3866f-e9df-420b-b7ee-7878465530ea", // "Case Conference" in CaseManager becomes "NSW WC Medical Case Conference" in NotusPoint (fuzzy match 84%)
  "2e7b5f73-2a6a-41ed-93b5-72f235d7053b": null, // "Case management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d1566a37-f240-4263-a1c4-f0cf583bf526": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3b60db80-260c-4cb7-b0cd-0be1d0707248": null, // "Case management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6728b5d9-7737-427d-bf1a-66a2256623d3": null, // "Case management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6b7bac51-31ce-434b-947a-2bc6c3b2a544": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "42d6ddd9-7c4c-42f5-8de8-1e957bc8cacd": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "fe8c0946-64ea-40f4-b6a7-4bd5339d3c43": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "a9f49d93-4c82-4a24-8681-b7e1d429bfe9": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6b6e7af8-6423-41ea-84cc-f0cda50f549a": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ff39febc-2717-4283-acc3-38b029177b90": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "a8fefcc1-809b-47dc-929e-11a669089cb3": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4e0c7541-e415-4240-9773-690633c3073e": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d2de7b74-8180-460e-96a6-bdbda50c7264": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "fa7e4771-5ede-4472-bfbf-9d85359c0d72": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "f8b4b180-1e3e-4637-9658-fc12b1011005": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5b2450ee-5903-4386-9f66-0f1afe544ad4": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "b478973c-a01e-4567-ab82-f9fd935048d7": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "691875d3-c00f-4701-92ae-b1bf84f8c679": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5441c0d9-f45a-4ccc-9833-e6022ec15373": null, // "Case Management" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "84243b40-0f24-4c46-9cff-ea3804694086": null, // "Case managerment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e2a5bbb3-250a-4d15-8b13-51fec28437d1": null, // "Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e38ccaef-d834-4d41-8c28-958bbc266c24": null, // "Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "9bb6d815-010b-4713-8a9c-f9a4355e81c1": null, // "Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c037ad64-c722-47a5-8744-8c7fd6b029db": null, // "Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "070b63d7-06a6-4bf9-8d90-2a00d4da33d6": null, // "Coaching Only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6e82ed67-ec97-4a2c-8d7d-e4d21a7fc288": "76ea4087-072b-45bd-b077-110470fa2fd5", // "Comcare (Codes) Activities of Daily Living Assessment" in CaseManager becomes "Comcare (Codes) Activities of Daily Living Assessment" in NotusPoint
  "42f714ce-3c8c-41e0-86a8-f02cac4a4b09": "9c025f5f-e008-426b-bb8a-ad113fa173af", // "Comcare (Codes) Comp Rehabilitation Assessment - S36" in CaseManager becomes "Comcare (Codes) Comp Rehabilitation Assessment - S36" in NotusPoint
  "4bcf261b-4a0c-477c-a66a-f55df8047f9a": "5053ac7e-d028-44b2-bea3-87bdb282d0e0", // "Comcare (Codes) Comp Rehabilitation Program - S37" in CaseManager becomes "Comcare (Codes) Comp Rehabilitation Program - S37" in NotusPoint
  "8354d4dc-ce97-4c42-a7d2-77b6e45fb3d7": "8e7eb569-6c8d-424b-b0c8-c04a761eee77", // "Comcare (Codes) Ergonomic Assessment" in CaseManager becomes "Comcare (Codes) Ergonomic Assessment" in NotusPoint
  "e242b544-a780-4bc0-be7d-e8dae793da69": "4f4e8b66-de4c-4d6d-92c8-88b23d39607b", // "Comcare (Codes) Functional Capacity Evaluation" in CaseManager becomes "Comcare (Codes) Functional Capacity Evaluation" in NotusPoint
  "d66691b1-2b67-4f47-bf49-68aa2a24d24c": "5684a232-b393-46d1-b422-3dd7ec737fc5", // "Comcare (Codes) Vocational Assessment" in CaseManager becomes "Comcare (Codes) Vocational Assessment" in NotusPoint
  "2c5beaa7-6bc5-4c9d-a80d-2ddfeef10605": "515840c0-f5ee-4077-b318-2a3c39db4ff1", // "Comcare (Codes) Work Capacity Assessment" in CaseManager becomes "Comcare (Codes) Work Capacity Assessment" in NotusPoint
  "fb41bbe5-8e5c-47af-840b-8707b869cff1": "90c2cc76-8fed-483b-aa43-606298ea6319", // "Comcare (Non Comp) Activities of Daily Living Assessment" in CaseManager becomes "Comcare (Non Comp) Activities of Daily Living Assessment" in NotusPoint
  "06c11eb9-29a5-4139-9c76-c72c767277e1": "f36e4000-45ea-446b-94d1-c4c39445d450", // "Comcare (Non Comp) Ergonomic Assessment" in CaseManager becomes "Comcare (Non Comp) Ergonomic Assessment" in NotusPoint
  "4090852d-f041-4269-9328-e2b03e4f4d4b": "a36170f4-5aa5-4a35-a699-d90ee9587e6b", // "Comcare (Non Comp) Initial Needs Assessment" in CaseManager becomes "Comcare (Non Comp) Initial Needs Assessment" in NotusPoint
  "f8bd5e9c-f69d-407d-a354-f79dd7805be7": "38367ddf-d056-4806-a1c5-515d022b3901", // "Comcare (Non Comp) Job Task Analysis" in CaseManager becomes "Comcare (Non Comp) Job Task Analysis" in NotusPoint
  "021800e6-6efd-4a86-91e3-3eec4f96e703": "a16ea9d0-b5cd-4691-bf26-944b355cd0f6", // "Comcare (Non Comp) Rehabilitation Program" in CaseManager becomes "Comcare (Non Comp) Rehabilitation Program" in NotusPoint
  "5cd4c4f2-bbd7-4f27-9c24-c04641450de3": "34576caf-3bd8-4a72-8101-6a1c77341912", // "Comcare (Non Comp) Vocational Assessment" in CaseManager becomes "Comcare (Non Comp) Vocational Assessment" in NotusPoint
  "001e1ae9-9229-4523-b4e8-6ec1a03f137a": "c773b3cb-56e6-41a6-af7d-4dfff0b63bd9", // "Comcare (Non Comp) Workplace Assessment" in CaseManager becomes "Comcare (Non Comp) Workplace Assessment" in NotusPoint
  "1ae26c8d-8112-413f-a552-b0c9beb686a8": null, // "Complex OT Intervention" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8f356879-3abe-4ffa-9bc5-88d77971ca39": null, // "Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "662dc45a-b1b7-42b3-bac5-cea12b5584c4": null, // "Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "168bde13-05e5-4d20-8422-e26df7247eb2": null, // "Create SDP" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c5b5d205-a5fa-4c1a-8cde-bc4a2c6e4499": null, // "Dependency Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c7b17213-c293-4750-b915-d5105f905249": "e9c9a0d3-fe44-4dff-8c1d-009d8e175a6a", // "Direct Activities of Daily Living Assessment" in CaseManager becomes "Direct Activities of Daily Living Assessment" in NotusPoint
  "0f566538-282d-4458-8ba9-17287fb673cf": "698ecc8c-de23-4d5a-98d0-92ae869c1d4e", // "Direct Business Coaching" in CaseManager becomes "Direct Business Coaching" in NotusPoint
  "d4c2d057-24fb-444a-8d12-359977611826": "ea1f62eb-7ca9-4ec7-bb06-cc90047790f2", // "Direct Ergonomic Assessment" in CaseManager becomes "Direct Ergonomic Assessment" in NotusPoint
  "5e68ffe3-2bde-43e1-8108-2e0ba861a832": "cfadb2b2-c145-453b-9a81-8edb607a7811", // "Direct Initial Needs Assessment" in CaseManager becomes "Direct Initial Needs Assessment" in NotusPoint
  "459f80b9-047c-4c21-9e48-5236163a5487": "d4b6e812-bfef-4e50-ae32-1e2af3361522", // "Direct Job Task Analysis" in CaseManager becomes "Direct Job Task Analysis" in NotusPoint
  "f0e68374-0d25-47d6-9723-ec8295b1456f": "a7eee4b3-7423-4866-919e-3c0cb6291a2f", // "Direct RTW" in CaseManager becomes "Direct RTW" in NotusPoint
  "0c900a83-0d56-40d6-af41-3ad4ee9eabe0": "09529804-b4d5-4ab3-9c4e-b75106dd3b7e", // "Direct Secondment" in CaseManager becomes "Direct Secondment" in NotusPoint
  "f87fd404-d1e7-4260-9247-41432745a074": "6bf99234-9c3c-4786-90bc-0ff625f2fa82", // "Direct Vocational Assessment" in CaseManager becomes "Direct Vocational Assessment" in NotusPoint
  "3c0edf2c-67d8-4556-95b1-5d56caa2d819": "1d6955dd-6d98-403d-9181-991f175d31c6", // "Direct Workplace Assessment" in CaseManager becomes "Direct Workplace Assessment" in NotusPoint
  "5cd3e5e2-9470-4753-b0c9-652f2804413d": null, // "Driving Asessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "75bc3f6c-4900-4a9e-9f18-130c916f41e9": "199244ce-264b-49ea-801d-2f0437325050", // "Driving Assessment" in CaseManager becomes "WC QLD Driving Assessment" in NotusPoint (fuzzy match 86%)
  "c6884e19-21bc-4be4-9e07-6784ca5e78a3": "199244ce-264b-49ea-801d-2f0437325050", // "Driving Assessment" in CaseManager becomes "WC QLD Driving Assessment" in NotusPoint (fuzzy match 86%)
  "6974d59a-cdfd-4b4a-98c5-d858e390f2b4": "10dcf1da-3424-4dc1-aea0-b1176cdb8314", // "DVA Activities of Daily Living Assessment" in CaseManager becomes "DVA Activities of Daily Living Assessment" in NotusPoint
  "1865c643-a1ef-4f52-b3e8-449d6ecede27": "209ca584-5aa8-4e79-b979-d3487a3a2979", // "DVA Plan Management" in CaseManager becomes "DVA Plan Management" in NotusPoint
  "a708be7b-4d59-4b6d-ad11-c07c161c270c": "10e53b58-2b87-453e-bb2c-338fc8c70946", // "DVA VP Plan Management" in CaseManager becomes "DVA VP Plan Management" in NotusPoint
  "537070bb-b418-46b3-baf7-848963a571f4": null, // "EML Activities of Daily Living Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6184d8fe-0ca0-414f-857c-39e1fc868b66": null, // "ep" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2e3e9024-3c03-4f4e-9d5f-0ea2bdbd35c3": null, // "EP Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "45ff483b-908f-470e-89af-35e35026cbf1": null, // "EP assistance and Job Coaching" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "97da9380-3803-4932-a750-3786b304cc56": null, // "EP Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3f8e3f7f-3e9c-4c91-af25-fcac049b7d11": null, // "EP/Work conditioning program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "66049f9e-3939-497f-a1bd-eec9a0ee5a3f": null, // "Ergonomic Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "9440e89d-6793-420d-aa8b-838aa71b605d": null, // "Ergonomic Evaluation - In person comprehensive" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ce984c05-c8ac-4fd2-a743-3448fbbf5b29": null, // "ESL Classes" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "06271be8-652a-4c25-bd5c-a88374fd653d": null, // "Evaluation" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "70389070-8cdf-4285-b0eb-c7dbc8bf6098": null, // "Evaluation and Plan" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "f0118670-0954-4445-a302-a3a917d4b262": "4bc64959-4561-42da-9b64-f49d1a9f81a8", // "FCE/RTW - Same Employer" in CaseManager becomes "LI RTW Same Employer" in NotusPoint (fuzzy match 86%)
  "88370bcb-27db-46a1-8336-9217c6352595": null, // "FIM, CANS" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "fec1331f-c38a-4a7b-95cb-96048973f245": null, // "FRED" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "fbbeb769-9e25-49d9-a838-4026e2e44d9b": null, // "Functional Capacity Evaluation" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5ffcf6db-909a-4091-8d85-cab61be0d5c6": null, // "Functional Job description" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2cd617f1-1b16-4e0e-b9a8-89dc802490de": null, // "Gap Analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "da433e5c-1014-4a3c-9275-ff6342f5d3ab": null, // "GRTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7b507229-fe66-4393-8808-0a651c451547": null, // "GRTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "89c389e7-cd71-40a4-8c33-f7b34e1ac5ac": null, // "GRTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "123718b5-935d-4ad4-a20a-d568d454f001": null, // "GRTWP" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4ce4e344-9be2-46f4-b59f-bc1127ad85b3": "9d7cb532-c4bd-4736-b703-5969dc4e8e29", // "Home Assessment" in CaseManager becomes "WC QLD Home Modifications Assessment" in NotusPoint (fuzzy match 84%)
  "19df3aca-76ac-4dd1-b47e-a93e4c256c17": "9d7cb532-c4bd-4736-b703-5969dc4e8e29", // "Home Assessment" in CaseManager becomes "WC QLD Home Modifications Assessment" in NotusPoint (fuzzy match 84%)
  "20d0688f-42f3-477b-8091-e9426e6fe59d": "9d7cb532-c4bd-4736-b703-5969dc4e8e29", // "Home Assessment" in CaseManager becomes "WC QLD Home Modifications Assessment" in NotusPoint (fuzzy match 84%)
  "99ccf6e5-a4f7-4e5c-b736-bccd111464ec": null, // "Home Assessment Only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8b1301a7-eac5-4803-bdb4-41a0fc72e248": "da7c012a-2b6e-4bff-a097-442b2e0431f7", // "Host employer placement" in CaseManager becomes "WC QLD Host Employer Placement" in NotusPoint (fuzzy match 86%)
  "249600ec-3909-44b7-81c0-d081ab2b327c": "da7c012a-2b6e-4bff-a097-442b2e0431f7", // "Host Employer Placement" in CaseManager becomes "WC QLD Host Employer Placement" in NotusPoint (fuzzy match 86%)
  "e27c001a-4fe3-4cc8-a404-d3635c92d6ab": "da7c012a-2b6e-4bff-a097-442b2e0431f7", // "Host Placement" in CaseManager becomes "WC QLD Host Employer Placement" in NotusPoint (fuzzy match 84%)
  "1bb76618-88a4-46bf-8c41-dfe831a4b32d": "a0da9aa5-9815-44ab-9df8-dd038c79aefa", // "iCare Activities of Daily Living Assessment" in CaseManager becomes "iCare Activities of Daily Living Assessment" in NotusPoint
  "d5459eeb-3135-4128-82d1-21c6fc37928e": "c37d91f3-5329-4705-ae35-2c6b67223b8e", // "iCare Case Management" in CaseManager becomes "iCare Case Management" in NotusPoint
  "9a21bf0b-f594-413f-85b6-c0d55c29b3ba": null, // "Initial Needs Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "66420005-7f50-46b3-a13f-fdcfdf2134c6": null, // "Initial Rehab Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "96ed2b90-1e26-454b-bdab-1f8440f80b00": null, // "Injury Management Plan" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8fc88b94-5ba0-4cd4-859a-6333e03198d5": null, // "Insignia TPD Pilot" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "eef8afd4-b18e-4740-a24e-cbba745a0cd6": null, // "internal" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8323859d-29eb-42e1-979c-43ce732bc0c5": null, // "Job Attached RTW Support" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "037c6c2e-26a8-4116-a70f-a35132695616": "619d4689-e9fe-4999-92b9-a3da55322232", // "Job Preparation" in CaseManager becomes "Self Insured WCQ Job Preparation Services" in NotusPoint (fuzzy match 82%)
  "2998eac9-5049-47aa-9636-fbdade843cca": null, // "Job Seeking" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "faa4b157-7053-48b4-8786-ddc2fc69579f": null, // "job seeking" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "748385dc-6e90-448f-84b9-a8102e151696": null, // "Job Seeking" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3177e9c5-1871-45a6-a3cb-9cae1cf73164": null, // "Job Seeking" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e6ac4eaf-c707-4100-8aba-a58aa916e804": null, // "Job Seeking" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "0d4fafbb-b8ba-4779-8cc3-2f2c9dfd7b23": null, // "Job Seeking" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c9141932-4819-49bd-aa42-7e2ac162b028": null, // "Job Seeking Activities" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ed692841-fcd5-4261-a8e6-23f4c476a7a8": null, // "Job seeking activities" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "bf007fbf-1565-4c8c-b080-8be3cb985c7d": "73afad02-2f9a-4cd0-8f81-918c675a3b80", // "job seeking assistance" in CaseManager becomes "Self Insured WCQ Job Seeking Assistance" in NotusPoint (fuzzy match 84%)
  "432b4479-b436-47a7-af8e-75c0d4e24a67": "73afad02-2f9a-4cd0-8f81-918c675a3b80", // "Job Seeking Assistance" in CaseManager becomes "Self Insured WCQ Job Seeking Assistance" in NotusPoint (fuzzy match 84%)
  "a756a64b-15d9-4f77-a9d5-d0b052345411": null, // "Job Seeking Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7dcf7d96-fb6f-4a00-88cf-64a0c139716b": null, // "Job Seeking Skills Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "b98bdba4-2741-48f3-ac57-cc9ee8ca85c6": null, // "job seeking support" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "04fec03c-3d8e-4c9f-9193-ae9573ee0472": null, // "Job Support and Seeking (New ER)" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ac36c5a1-b841-41b1-aadc-65287121da61": null, // "Job Task Analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "973d6a17-8156-4cd5-9113-4ce370e4b3dc": null, // "job task analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "487593b2-c4ad-4758-943e-47f53193c822": null, // "Job unattached RTW Support" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "f254eac0-6497-4810-a24b-48b14b44be2c": null, // "Labour Market Analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "88bcc1cd-6c07-4dfb-9020-5887fbc116a9": null, // "Left hand injury" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "373a8f5d-08d2-4b02-8f9a-63f36919511a": "05c853fc-86cb-454e-96d7-ac56a767c07d", // "LI Acenda Activities of Daily Living Assessment" in CaseManager becomes "LI Acenda Activities of Daily Living Assessment" in NotusPoint
  "6d4cc541-9ea7-4a7c-9527-ad1338fc3651": "7fd49a4f-0d1f-4c82-8fd9-103fbafe342a", // "LI Acenda Early Engagement" in CaseManager becomes "LI Acenda Early Engagement" in NotusPoint
  "2a13c47c-03e4-40fc-b324-df28274f0726": "f88b1542-f7f5-4f81-be10-723c5dff1833", // "LI Acenda Ergonomic Assessment" in CaseManager becomes "LI Acenda Ergonomic Assessment" in NotusPoint
  "a11aa4cb-64cd-482f-989b-b9e58ad9e157": "cc3bd6d8-e4c6-4e28-bc2d-d2d7d959f78f", // "LI Acenda Functional Capacity Assessment - Physical" in CaseManager becomes "LI Acenda Functional Capacity Assessment - Physical" in NotusPoint
  "453edfec-b97d-4f08-921b-135bc9c43900": "ea0680d5-d179-4255-aeca-49b8822d8616", // "LI Acenda Functional Capacity Assessment - Psychological" in CaseManager becomes "LI Acenda Functional Capacity Assessment - Psychological" in NotusPoint
  "eb0533c9-5280-4dde-85f4-0974f795551e": "b5e13825-47ad-448f-8dad-e6939130c201", // "LI Acenda Initial Needs Assessment" in CaseManager becomes "LI Acenda Initial Needs Assessment" in NotusPoint
  "4ddfdfb2-6135-4af8-b1a9-9c89b401b013": "59aff010-5539-4c4f-86ca-4f15578bae73", // "LI Acenda Labour Market Analysis" in CaseManager becomes "LI Acenda Labour Market Analysis" in NotusPoint
  "cd360429-521b-44e8-9c64-c9a9811fc0bc": "3952cef9-ecd2-4767-8e71-663c97e40123", // "LI Acenda MGD Program" in CaseManager becomes "LI Acenda MGD Program" in NotusPoint
  "35145306-313c-4249-aa0f-e83dd395bee6": "5078b435-2f3d-484b-8d27-45d96f5c5e73", // "LI Acenda New Employer - Job Seeking Activities" in CaseManager becomes "LI Acenda New Employer - Job Seeking Activities" in NotusPoint
  "5879e140-85f6-4bef-8db7-78c876da14fa": "67f69659-e951-40ab-838f-320a646b7163", // "LI Acenda Pivotl Business Coaching" in CaseManager becomes "LI Acenda Pivotl Business Coaching" in NotusPoint
  "a6056506-fe12-4a54-b065-644cca7564dc": "c4f82127-7ba8-402f-b1a4-b45702413c63", // "LI Acenda Pivotl Business Gap Analysis" in CaseManager becomes "LI Acenda Pivotl Business Gap Analysis" in NotusPoint
  "c0690d67-218b-4ec8-b386-be9e2048e23e": "2c3365ad-38df-4257-9199-e0ba76ba637d", // "LI Acenda Pivotl Business Mentoring" in CaseManager becomes "LI Acenda Pivotl Business Mentoring" in NotusPoint
  "3d887c26-c68d-4855-9388-6000b15d0c80": "8bdbc697-7f28-489e-b48e-b70f5be56766", // "LI Acenda Pivotl Executive Career Analysis" in CaseManager becomes "LI Acenda Pivotl Executive Career Analysis" in NotusPoint
  "3a8dee4c-4f82-46ec-95e3-1f09a763b86a": "fb7da986-5b1b-49ae-b6f6-23eecd97118a", // "LI Acenda Pivotl Executive Coaching" in CaseManager becomes "LI Acenda Pivotl Executive Coaching" in NotusPoint
  "a3b1576e-dca2-4e3a-8bd7-2e3d80c923e6": "c1e0123e-ad64-437b-8fa9-df9f3ea7bbde", // "LI Acenda Pivotl Viability Assessment" in CaseManager becomes "LI Acenda Pivotl Viability Assessment" in NotusPoint
  "975c9e9b-c55b-425c-962c-8989e9d45a53": "43d3c961-2c7a-4522-a94d-d2e655d7a5d2", // "LI Acenda Pre-Vocational Services" in CaseManager becomes "LI Acenda Pre-Vocational Services" in NotusPoint
  "a6a16d46-99ec-4723-a1e6-1a64800f4999": "26bc6704-2e6a-4ec4-9689-010ff96569c6", // "LI Acenda RTW New Employer - Vocational Counselling" in CaseManager becomes "LI Acenda RTW New Employer - Vocational Counselling" in NotusPoint
  "6b53a43b-f596-47a1-9624-fb64bd9eb4da": "4e591760-ffc5-4d08-a2d2-6cefc55e5b38", // "LI Acenda RTW Same Employer" in CaseManager becomes "LI Acenda RTW Same Employer" in NotusPoint
  "bdc4ab62-9cd2-4e78-a63e-514e69a3373e": "e791740c-1beb-40ab-8f03-b272214c0b55", // "LI Acenda Social Support for Work Readiness" in CaseManager becomes "LI Acenda Social Support for Work Readiness" in NotusPoint
  "50d0fb63-dfe7-49ee-93ca-631f3cc613a0": "04874624-8bd0-4c4e-9e29-07397dadb1b7", // "LI Acenda Streamline Job Task Analysis" in CaseManager becomes "LI Acenda Streamline Job Task Analysis" in NotusPoint
  "f2e5f7d4-e8db-429c-b781-82cbd0b658a6": "5b2083ae-b0c9-4258-ad57-740f474d29d3", // "LI Acenda Task Analysis" in CaseManager becomes "LI Acenda Task Analysis" in NotusPoint
  "24e1acdf-df02-448e-b894-55a72cbb6f31": "12ed4aed-4fe2-4b51-954a-2a7e537efd11", // "LI Acenda Transferrable Skills Assessment" in CaseManager becomes "LI Acenda Transferrable Skills Assessment" in NotusPoint
  "df9c10f7-5285-47de-8c46-491fd1eb51bb": "981f311b-a886-4849-b63e-14775bc00283", // "LI Acenda Triage Services" in CaseManager becomes "LI Acenda Triage Services" in NotusPoint
  "36a0733a-f6f6-46a4-af7a-6c33c7048e1b": "db602a5d-7fe5-4130-893d-41ef9c334af1", // "LI Acenda Uvida Seeds Wellbeing Program" in CaseManager becomes "LI Acenda Uvida Seeds Wellbeing Program" in NotusPoint
  "2c10046a-aeab-428b-b0ba-955c9615aaae": "74e969b5-8799-4ce1-ae88-66da9a799be6", // "LI Acenda Vocational Assessment" in CaseManager becomes "LI Acenda Vocational Assessment" in NotusPoint
  "83c2dccd-29c2-4da2-81fc-5c842ed7cb24": "c123dced-9a26-47ac-9b38-35304bde985c", // "LI Acenda Workplace Assessment" in CaseManager becomes "LI Acenda Workplace Assessment" in NotusPoint
  "a15621e2-1919-45d8-a861-a204cd5f2ba2": "a0415237-12ed-43ac-8463-78d03569f95e", // "LI Activities of Daily Living Assessment" in CaseManager becomes "LI Activities of Daily Living Assessment" in NotusPoint
  "7726eb9e-d032-41f1-8253-bda58f67abc0": "52cac576-d79a-4dae-a281-54a047fe20d9", // "LI AIA Activities of Daily Living Assessment" in CaseManager becomes "LI AIA Activities of Daily Living Assessment" in NotusPoint
  "75ee94a8-4beb-46eb-9479-06ba3b544325": "bef33dca-c33c-4637-8f23-513ca6a71821", // "LI AIA Early Engagement" in CaseManager becomes "LI AIA Early Engagement" in NotusPoint
  "c2dd746e-4c84-47a3-a039-86f1099eee71": "ad2b2f4d-fa82-4d10-ab84-a194427d91e7", // "LI AIA Ergonomic Assessment" in CaseManager becomes "LI AIA Ergonomic Assessment" in NotusPoint
  "065d7972-3458-47ea-b524-5400e30ac083": "73f45082-6c37-43f3-b0af-142f6ae8b75e", // "LI AIA Functional Capacity Assessment - Physical" in CaseManager becomes "LI AIA Functional Capacity Assessment - Physical" in NotusPoint
  "b5960764-04c4-463a-98df-24e5a0ba66f1": "b957379e-deb4-4268-9ccc-8f4467e6ae80", // "LI AIA Functional Capacity Assessment - Psychological" in CaseManager becomes "LI AIA Functional Capacity Assessment - Psychological" in NotusPoint
  "51cbd4c6-96b8-4cfe-8535-a3d2b3a76b19": "6468ff03-8e3b-4997-abb8-93c1df80e767", // "LI AIA Initial Needs Assessment" in CaseManager becomes "LI AIA Initial Needs Assessment" in NotusPoint
  "e856f9d0-b3e5-4954-b811-76a2520fd6db": "ff27facc-994a-49ae-92f0-699681f93619", // "LI AIA Labour Market Analysis" in CaseManager becomes "LI AIA Labour Market Analysis" in NotusPoint
  "55cacd4d-b9c4-45cf-a63a-9a1a06c6c07f": "6269a63b-346a-47f3-94f2-0a99303ba283", // "LI AIA MGD Program" in CaseManager becomes "LI AIA MGD Program" in NotusPoint
  "3ae1a9fd-506b-482a-b5f8-1f2b7383f7f4": "fda427f0-8cfc-463e-a371-9bef5741b2e1", // "LI AIA New Employer - Job Seeking Activities" in CaseManager becomes "LI AIA New Employer - Job Seeking Activities" in NotusPoint
  "90bd0173-ffdf-4d09-bab6-69573d480d21": "8081b697-dc80-4342-9713-75c7a4c3f99e", // "LI AIA Pivotl Business Coaching" in CaseManager becomes "LI AIA Pivotl Business Coaching" in NotusPoint
  "54ea992b-37ae-43ff-978b-b262e341a37e": "53297298-a897-43a0-9d6d-c2b76ad9c591", // "LI AIA Pivotl Business Gap Analysis" in CaseManager becomes "LI AIA Pivotl Business Gap Analysis" in NotusPoint
  "e13a43d0-6c42-439c-a310-7661e93996f5": "004d888f-bfb4-4754-a842-17120d993970", // "LI AIA Pivotl Business Mentoring" in CaseManager becomes "LI AIA Pivotl Business Mentoring" in NotusPoint
  "62fc7647-41f3-4df9-91c9-78725608a6dc": "1718e2ea-eca9-426d-895a-ae650eb0d2ce", // "LI AIA Pivotl Executive Career Analysis" in CaseManager becomes "LI AIA Pivotl Executive Career Analysis" in NotusPoint
  "b4762477-27b2-4877-a730-86d162e76e47": "77c45f4e-d54f-4ddb-80c6-a2c840e10889", // "LI AIA Pivotl Executive Coaching" in CaseManager becomes "LI AIA Pivotl Executive Coaching" in NotusPoint
  "2f4244b0-ba2b-482c-bacc-7a6d6a8b0aa8": "47679ac0-feff-4de0-82a2-0dfbf443ef1f", // "LI AIA Pivotl Viability Assessment" in CaseManager becomes "LI AIA Pivotl Viability Assessment" in NotusPoint
  "accd0fcf-6b86-491a-82d9-097a65f95f60": "c5d5b974-0f5e-440c-bbe7-063bdc6d8416", // "LI AIA Pre-Vocational Services" in CaseManager becomes "LI AIA Pre-Vocational Services" in NotusPoint
  "8cecdec2-decb-4074-9216-1fb41ac33bf5": "d44a1bec-70db-4097-aef0-ae28b9aaa27b", // "LI AIA RTW New Employer - Vocational Counselling" in CaseManager becomes "LI AIA RTW New Employer - Vocational Counselling" in NotusPoint
  "be8b556b-b024-48c7-b22e-da8ebff12585": "26619b18-817b-4bfe-9d0b-963b3b87b650", // "LI AIA RTW Same Employer" in CaseManager becomes "LI AIA RTW Same Employer" in NotusPoint
  "59773190-294b-4c5c-b0ce-fee3c0d70be4": "9fd6806a-2f4e-4a0d-b517-33a19585b336", // "LI AIA Social Support for Work Readiness" in CaseManager becomes "LI AIA Social Support for Work Readiness" in NotusPoint
  "80a5b441-0c13-4e0e-8aa5-5e8919f0e517": "e93df71d-4636-474e-905c-fb775c628eef", // "LI AIA Streamline Job Task Analysis" in CaseManager becomes "LI AIA Streamline Job Task Analysis" in NotusPoint
  "49e85392-0d5a-4323-903c-60f0176901ef": "3ff07952-52e1-4e4a-9d7c-c16683330e40", // "LI AIA Task Analysis" in CaseManager becomes "LI AIA Task Analysis" in NotusPoint
  "f4147ed0-5e37-480a-a4e1-439e2e42ceba": "f9d35b76-0305-44a3-9fde-7c50df8f6257", // "LI AIA Transferrable Skills Assessment" in CaseManager becomes "LI AIA Transferrable Skills Assessment" in NotusPoint
  "a6ba9e0f-69ba-41d4-8f9c-d5633ad0dfd7": "3da98c83-afea-4cd3-b952-7e01e66d5b38", // "LI AIA Triage Services" in CaseManager becomes "LI AIA Triage Services" in NotusPoint
  "371a3471-d386-4265-ad49-3a95dc764768": "77a7ca4f-0b69-434e-b064-315bf10820c6", // "LI AIA Uvida Seeds Wellbeing Program" in CaseManager becomes "LI AIA Uvida Seeds Wellbeing Program" in NotusPoint
  "ea58cc68-bd25-4866-9698-0245337745cc": "4efbc21a-0256-4326-872e-25f82877ed31", // "LI AIA Vocational Assessment" in CaseManager becomes "LI AIA Vocational Assessment" in NotusPoint
  "a9367fff-b912-4e17-bfba-bb0aee52c55d": "49f2b9d6-b450-4117-83a7-3070b1c68f53", // "LI AIA Workplace Assessment" in CaseManager becomes "LI AIA Workplace Assessment" in NotusPoint
  "5a92c2f8-5c53-455a-91ac-04bb63eea6ef": "2f292165-60bf-4284-8af3-56ec581bec12", // "LI Early Engagement" in CaseManager becomes "LI Early Engagement" in NotusPoint
  "474181d3-87ba-4cab-a4a6-857a8a15bf52": "056d80a4-c0f8-4bf6-8c27-7c58de77ff59", // "LI Ergonomic Assessment" in CaseManager becomes "LI Ergonomic Assessment" in NotusPoint
  "2e40ea31-5330-4274-9ccd-eb55ca6390a8": "5c68c331-9762-4b10-a60e-eb0d85d64513", // "LI Functional Capacity Assessment - Physical" in CaseManager becomes "LI Functional Capacity Assessment - Physical" in NotusPoint
  "e65dbb1b-2989-4cd4-b3e1-022be505ccfd": "a6c7b2f6-1ac9-42e1-adf2-3872c2b10975", // "LI Functional Capacity Assessment - Psychological" in CaseManager becomes "LI Functional Capacity Assessment - Psychological" in NotusPoint
  "2544c7e8-f811-445c-985d-111221846fd7": "11f9705c-5942-4c34-94e6-e05962c4f157", // "LI Initial Needs Assessment" in CaseManager becomes "LI Initial Needs Assessment" in NotusPoint
  "a9b72456-1b18-4534-9cc7-4322cec7d643": "8321f04c-b662-447f-8779-aededdad05a9", // "LI Labour Market Analysis" in CaseManager becomes "LI Labour Market Analysis" in NotusPoint
  "6fa3425e-b473-4b28-98a4-a96f5c106736": "4e396bea-f07d-422d-b6f4-0debb2d30686", // "LI Metlife Activities of Daily Living Assessment" in CaseManager becomes "LI Metlife Activities of Daily Living Assessment" in NotusPoint
  "d85fe2f3-fc02-45bf-a0cd-3c8340365d25": "91fabc1e-fbc9-4326-adcf-3f486a14f146", // "LI Metlife Early Engagement" in CaseManager becomes "LI Metlife Early Engagement" in NotusPoint
  "199c1e63-7bc8-42bb-9e75-b749acc15534": "5ac0c2f0-8aa9-40c3-9856-45974d84fb4a", // "LI Metlife Ergonomic Assessment" in CaseManager becomes "LI Metlife Ergonomic Assessment" in NotusPoint
  "9b8fdde6-03e9-4a15-af8e-a36c0ef602ff": "b3736487-caff-40a1-99d1-5bf5af6ed85b", // "LI Metlife Functional Capacity Assessment - Physical" in CaseManager becomes "LI Metlife Functional Capacity Assessment - Physical" in NotusPoint
  "1131709e-b1e8-4856-9a5f-276eb0734a49": "ee0dddbe-81f3-4547-983b-25d964692d1b", // "LI Metlife Functional Capacity Assessment - Psychological" in CaseManager becomes "LI Metlife Functional Capacity Assessment - Psychological" in NotusPoint
  "0f76525c-d3b2-47c9-82cb-dfff792856d4": "548abcac-8a6c-4fb5-8999-7016cbf42b69", // "LI Metlife Initial Needs Assessment" in CaseManager becomes "LI Metlife Initial Needs Assessment" in NotusPoint
  "79b90c74-67f7-42ad-a95f-a87576030098": "7d2d915a-6413-4809-90cd-d0aa8a1f8ca3", // "LI Metlife Labour Market Analysis" in CaseManager becomes "LI Metlife Labour Market Analysis" in NotusPoint
  "650b81f0-da01-4efd-8d3c-ab5cabfaf723": "6043f898-0292-47fc-82ac-f8adf2aa67e6", // "LI Metlife MGD Program" in CaseManager becomes "LI Metlife MGD Program" in NotusPoint
  "226028e6-8298-4d65-8c34-48416ff939dc": "9b111a47-ed47-470d-b7b1-b73dea1773e6", // "LI Metlife New Employer - Job Seeking Activities" in CaseManager becomes "LI Metlife New Employer - Job Seeking Activities" in NotusPoint
  "cd2ab3c8-99ac-4443-bc3d-74fa5954ba66": "9590b6db-7c09-4d47-a8b6-bd2b7788d1f6", // "LI Metlife Pivotl Business Coaching" in CaseManager becomes "LI Metlife Pivotl Business Coaching" in NotusPoint
  "41c88277-f4c4-438b-867d-0cbd122d2c0f": "ebc1e044-1460-4ecc-bfb9-6d1b9cda9f00", // "LI Metlife Pivotl Business Gap Analysis" in CaseManager becomes "LI Metlife Pivotl Business Gap Analysis" in NotusPoint
  "d3868ead-b0d3-463f-9f20-1df6c1aff8d9": "8c76a78b-d10c-453d-817f-83e0d5154690", // "LI Metlife Pivotl Business Mentoring" in CaseManager becomes "LI Metlife Pivotl Business Mentoring" in NotusPoint
  "122bbfd6-4b32-4909-b069-7a4a66e428b5": "e4baa145-d7ac-478f-a24f-74d72477d7b3", // "LI Metlife Pivotl Executive Career Analysis" in CaseManager becomes "LI Metlife Pivotl Executive Career Analysis" in NotusPoint
  "82107a61-d5b3-4991-b9b1-f7447fb936a9": "f53e92d8-5a2e-45a8-9edc-058dd8a4c7f8", // "LI Metlife Pivotl Executive Coaching" in CaseManager becomes "LI Metlife Pivotl Executive Coaching" in NotusPoint
  "5bb9156a-4a56-4c05-b3c5-b3a3f819598a": "efb97773-fe12-4c58-8120-5c687cefcfb3", // "LI Metlife Pivotl Viability Assessment" in CaseManager becomes "LI Metlife Pivotl Viability Assessment" in NotusPoint
  "79c6d299-a53d-43ad-ab1f-6d0eca167bc5": "97b80993-c797-4c60-b014-ecf6d4b03ebe", // "LI Metlife Pre-Vocational Services" in CaseManager becomes "LI Metlife Pre-Vocational Services" in NotusPoint
  "65562a36-b53f-48ce-8346-3586095c9974": "c14d54c2-c2ba-42c2-be95-41d5c6940c75", // "LI Metlife RTW New Employer - Vocational Counselling" in CaseManager becomes "LI Metlife RTW New Employer - Vocational Counselling" in NotusPoint
  "4f4b7201-82da-4bad-8c75-475d7222b64e": "f645ecc4-d831-4981-95a6-b2e25653115d", // "LI Metlife RTW Same Employer" in CaseManager becomes "LI Metlife RTW Same Employer" in NotusPoint
  "d535e849-3b83-494e-8972-3d16dbf8fe93": "7ffae54a-d946-482e-9a8c-d91f2b4cf23d", // "LI Metlife Social Support for Work Readiness" in CaseManager becomes "LI Metlife Social Support for Work Readiness" in NotusPoint
  "81cee4da-8825-4013-b1b8-6908e9d9257d": "d73f12d9-318b-4464-949e-a6cc51b7e4dc", // "LI Metlife Streamline Job Task Analysis" in CaseManager becomes "LI Metlife Streamline Job Task Analysis" in NotusPoint
  "4fe799cf-26e7-4bf8-944d-f31da023a915": "b19a2afe-85c7-47f9-bddf-600c4cb4d3e0", // "LI Metlife Task Analysis" in CaseManager becomes "LI Metlife Task Analysis" in NotusPoint
  "c74ed5d2-186b-451a-8a15-c67b3e38b2d6": "5a25273a-3b72-43f4-bc1e-5710cde9f79b", // "LI Metlife Transferrable Skills Assessment" in CaseManager becomes "LI Metlife Transferrable Skills Assessment" in NotusPoint
  "36707126-bc49-4334-9041-d26f47b974f4": "152fa8ae-3d83-4c7e-bb98-098f13efcf34", // "LI Metlife Triage Services" in CaseManager becomes "LI Metlife Triage Services" in NotusPoint
  "e82b6cc6-7ca1-4dc7-8124-447bb77e98b5": "70cf9dc2-2aed-41d0-91ae-bbe3d593e541", // "LI Metlife Uvida Seeds Wellbeing Program" in CaseManager becomes "LI Metlife Uvida Seeds Wellbeing Program" in NotusPoint
  "27756844-040c-4f1f-abc5-da646f5ba9f8": "9367a01d-d4cf-4827-a848-c4157e319458", // "LI Metlife Vocational Assessment" in CaseManager becomes "LI Metlife Vocational Assessment" in NotusPoint
  "0bbd7271-63c2-4898-b05e-f68b8338c79e": "8fe9ce0f-7bd0-4cbc-a257-eac76013e76a", // "LI Metlife Workplace Assessment" in CaseManager becomes "LI Metlife Workplace Assessment" in NotusPoint
  "362985ee-6c27-4786-a9bc-f346bd06d1cd": "d22277cc-dfee-4f78-adb7-ff5bdceb85ae", // "LI MGD Program" in CaseManager becomes "LI MGD Program" in NotusPoint
  "4da0b8b2-74ba-4fd3-b8e0-cfb7ce4ec51b": "d8907103-7dc1-46e7-8cb5-767388d00544", // "LI New Employer - Job Seeking Activities" in CaseManager becomes "LI New Employer - Job Seeking Activities" in NotusPoint
  "04711d5e-a9ae-4063-86da-ac4207af2598": "cc6d7a5c-d54a-43e0-81ab-8ed5bfa8bd24", // "LI Pivotl Business Coaching" in CaseManager becomes "LI Pivotl Business Coaching" in NotusPoint
  "444e7749-00b4-47f9-b655-ee590a4f6b01": "90732c95-74e4-49d2-97e4-90acc3eb463e", // "LI Pivotl Business Gap Analysis" in CaseManager becomes "LI Pivotl Business Gap Analysis" in NotusPoint
  "61d69c81-312c-425c-b307-f49801462232": "c67edfa9-aa5f-4b4b-83aa-dd19355c16fc", // "LI Pivotl Business Mentoring" in CaseManager becomes "LI Pivotl Business Mentoring" in NotusPoint
  "e5f1ccea-fa5b-4471-83ee-0cae7c8ba10d": "4dc50de5-444c-47ed-8953-61c66f25beed", // "LI Pivotl Executive Career Analysis" in CaseManager becomes "LI Pivotl Executive Career Analysis" in NotusPoint
  "56136761-b1d4-4f90-9cda-9a74fb64008a": "bc5982b6-a75a-43e4-a7e4-3a5d9a92875d", // "LI Pivotl Executive Coaching" in CaseManager becomes "LI Pivotl Executive Coaching" in NotusPoint
  "0ba94367-9bf0-4c58-bfda-00d9bcc6bfe8": "7a5fdf8e-19f9-4665-9ae0-5b11150b3189", // "LI Pivotl Viability Assessment" in CaseManager becomes "LI Pivotl Viability Assessment" in NotusPoint
  "41c2f323-c0fe-49bd-93f0-defa26fe2542": "fb5095e3-624c-47fb-9a01-4e8029d50cca", // "LI Pre-Vocational Services" in CaseManager becomes "LI Pre-Vocational Services" in NotusPoint
  "e175ffda-13d1-49db-b43a-fa3eea0b0542": "0163af1d-2cf8-472f-95c4-0d28fb74d86b", // "LI RTW New Employer - Vocational Counselling" in CaseManager becomes "LI RTW New Employer - Vocational Counselling" in NotusPoint
  "cdd204d5-4a6a-4b1f-af3f-e7598cf7abd3": "4bc64959-4561-42da-9b64-f49d1a9f81a8", // "LI RTW Same Employer" in CaseManager becomes "LI RTW Same Employer" in NotusPoint
  "e8d6586d-22fb-4f89-9472-dee0f7c82695": "04124214-5bfa-4476-ac2d-bb8bebc08b95", // "LI Social Support for Work Readiness" in CaseManager becomes "LI Social Support for Work Readiness" in NotusPoint
  "89b9da17-6709-462d-9a60-648c0e0ac882": "e99d7311-af07-41f7-ab46-804e1d261609", // "LI Streamline Job Task Analysis" in CaseManager becomes "LI Streamline Job Task Analysis" in NotusPoint
  "b1b04bca-62b2-408e-8ea1-19882a36b97a": "7656055e-899d-4c9f-8279-36d4c0fac87a", // "LI TAL Activities of Daily Living Assessment" in CaseManager becomes "LI TAL Activities of Daily Living Assessment" in NotusPoint
  "9e517e44-0224-4fe2-84cc-0b348a1d8166": "eac0ee8b-f742-458c-9eec-3e71451d8598", // "LI TAL Early Engagement" in CaseManager becomes "LI TAL Early Engagement" in NotusPoint
  "974da462-f9d8-4869-9427-349417acb9d9": "948fa036-c489-4ee0-bc35-db49331bcd84", // "LI TAL Ergonomic Assessment" in CaseManager becomes "LI TAL Ergonomic Assessment" in NotusPoint
  "a3242095-6296-40bf-96ee-26e1eb425978": "05d404f6-b972-4655-ac55-1620d3a5ae31", // "LI TAL Functional Capacity Assessment - Physical" in CaseManager becomes "LI TAL Functional Capacity Assessment - Physical" in NotusPoint
  "002d9f0d-76a4-4d3a-bb26-845830068040": "f47bf90e-39e4-41f0-9b30-f0fd1cfb4f3a", // "LI TAL Functional Capacity Assessment - Psychological" in CaseManager becomes "LI TAL Functional Capacity Assessment - Psychological" in NotusPoint
  "296f87ee-a276-41b7-a4d2-3644d04b1bf6": "443f41b2-1128-4e8f-ba1f-446d7ffa9405", // "LI TAL Initial Needs Assessment" in CaseManager becomes "LI TAL Initial Needs Assessment" in NotusPoint
  "f03b201a-004e-4b1c-8ced-0dbc110ba5c6": "14383424-dabe-434c-90ea-f23c15bf12e5", // "LI TAL Labour Market Analysis" in CaseManager becomes "LI TAL Labour Market Analysis" in NotusPoint
  "fecba744-6aad-491d-8c13-c9ed0a1b1ad1": "bd4d7f3e-aa4c-4e32-be36-70decdddaeed", // "LI TAL MGD Program" in CaseManager becomes "LI TAL MGD Program" in NotusPoint
  "83045b09-d70c-4664-895f-89723bc73cb5": "0168925a-c582-4693-a454-16535d72bb7d", // "LI TAL New Employer - Job Seeking Activities" in CaseManager becomes "LI TAL New Employer - Job Seeking Activities" in NotusPoint
  "2b41cfd4-ed11-474e-8850-f4c24c8421d7": "d4b032a8-3e88-4395-8d20-31a5a3170f5d", // "LI TAL Pivotl Business Coaching" in CaseManager becomes "LI TAL Pivotl Business Coaching" in NotusPoint
  "015ef6b0-520e-4427-a0c6-31d7d04df1e8": "b919c2de-44a9-4162-a164-ebadd9f1fbcf", // "LI TAL Pivotl Business Gap Analysis" in CaseManager becomes "LI TAL Pivotl Business Gap Analysis" in NotusPoint
  "53b1a3e6-7952-4fee-a3c4-5593e61631d2": "138d792a-d240-4896-89d0-104a94e1abc4", // "LI TAL Pivotl Business Mentoring" in CaseManager becomes "LI TAL Pivotl Business Mentoring" in NotusPoint
  "3ec563d2-17c5-4ab8-844c-3275e1ccaf5a": "f6256ce4-0099-4cb2-afaf-23a6393e21b1", // "LI TAL Pivotl Executive Career Analysis" in CaseManager becomes "LI TAL Pivotl Executive Career Analysis" in NotusPoint
  "63e2ed04-7d9b-4b6d-adf5-9da675bd269b": "4b2bfdef-a274-4f10-933e-cab5ab500a7c", // "LI TAL Pivotl Executive Coaching" in CaseManager becomes "LI TAL Pivotl Executive Coaching" in NotusPoint
  "ccf2661f-44e0-42f5-9043-9fbdd978760b": "d7698791-e112-45a8-8bda-c96ad666217e", // "LI TAL Pivotl Viability Assessment" in CaseManager becomes "LI TAL Pivotl Viability Assessment" in NotusPoint
  "09a15aff-792e-47e2-a582-0dced78b5dc1": "7a094804-8137-47ac-b905-af22ebd589ac", // "LI TAL Pre-Vocational Services" in CaseManager becomes "LI TAL Pre-Vocational Services" in NotusPoint
  "c1e0ad49-93a3-4784-8415-ffbaceae553c": "250ef271-f386-44c2-91d7-6fd8715a915c", // "LI TAL RTW New Employer - Vocational Counselling" in CaseManager becomes "LI TAL RTW New Employer - Vocational Counselling" in NotusPoint
  "2e2773d6-da4c-415f-8b0f-800c68571326": "a11823e5-88ad-4287-83a7-91b3688eacb0", // "LI TAL RTW Same Employer" in CaseManager becomes "LI TAL RTW Same Employer" in NotusPoint
  "5ff49c6b-27fa-40a8-ba13-c0adac6ae2f0": "25c4e1ed-ae04-402f-8b0c-67707dcd8f26", // "LI TAL Social Support for Work Readiness" in CaseManager becomes "LI TAL Social Support for Work Readiness" in NotusPoint
  "fe32893b-286d-4b76-8805-073c8dd8a724": "871b86fa-2309-482c-8967-a1dee31d345d", // "LI TAL Streamline Job Task Analysis" in CaseManager becomes "LI TAL Streamline Job Task Analysis" in NotusPoint
  "b3599609-169a-43a4-be98-81095e388aa8": "719fc3f7-880a-4e3d-8890-afde012b9909", // "LI TAL Task Analysis" in CaseManager becomes "LI TAL Task Analysis" in NotusPoint
  "513ffc00-0349-4455-a81e-0be3b2f650bb": "d0971016-5764-452d-8808-a2496d1a69b9", // "LI TAL Transferrable Skills Assessment" in CaseManager becomes "LI TAL Transferrable Skills Assessment" in NotusPoint
  "2e4f4f41-4a9a-4105-9b9c-ea797b9c0f2e": "79093d04-1a25-46a6-882f-1a24f151d02e", // "LI TAL Triage Services" in CaseManager becomes "LI TAL Triage Services" in NotusPoint
  "c4d7ec00-26c5-46f9-b373-86b3e853466e": "47b9569d-d6f7-4581-ab63-fb9fabb5adfd", // "LI TAL Uvida Seeds Wellbeing Program" in CaseManager becomes "LI TAL Uvida Seeds Wellbeing Program" in NotusPoint
  "78ce6423-72dc-401e-9ec5-cabc953d0ff6": "2167147c-d570-4b95-904f-fd21913d2833", // "LI TAL Vocational Assessment" in CaseManager becomes "LI TAL Vocational Assessment" in NotusPoint
  "58ad69ea-fb0d-4679-8690-73adfce128f7": "b4a43148-4fa4-4444-8705-6c63e462512d", // "LI TAL Workplace Assessment" in CaseManager becomes "LI TAL Workplace Assessment" in NotusPoint
  "6eed6e23-91c3-4658-9f31-2b70d0fd07ab": "594e6393-c2e7-4432-9e65-cfda574810d4", // "LI Task Analysis" in CaseManager becomes "LI Task Analysis" in NotusPoint
  "a1dcc3eb-0b32-41c1-abd1-f52d6c4ab632": "c75304eb-9e74-4762-a1c5-8c956096071d", // "LI Transferrable Skills Assessment" in CaseManager becomes "LI Transferrable Skills Assessment" in NotusPoint
  "3a5d613f-71de-4b38-a20f-188d8c16da77": "2b95cc0d-5f85-490d-9e4c-2f706fbffefb", // "LI Triage Services" in CaseManager becomes "LI Triage Services" in NotusPoint
  "cc2981c7-b128-49e0-baa5-0b5991e50de5": "7a6d0ac0-0a50-4bbf-82be-f4d5bae5450c", // "LI Uvida Seeds Wellbeing Program" in CaseManager becomes "LI Uvida Seeds Wellbeing Program" in NotusPoint
  "4b138b9d-cf38-4e3a-869c-1ff9bd7caa3f": "992f9b2b-5e2f-4369-a473-248bbe112b3a", // "LI Vocational Assessment" in CaseManager becomes "LI Vocational Assessment" in NotusPoint
  "ccea3cd5-4159-40d6-bc8f-04bf88f83573": "f3d394fe-136c-4ee3-a312-4a8435f61103", // "LI Workplace Assessment" in CaseManager becomes "LI Workplace Assessment" in NotusPoint
  "ddd2032c-6c30-4f95-86df-16c616dd1972": null, // "LMA" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7f0fbb08-7659-48e6-a5fb-e69db528c1f3": null, // "LMA" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "dde5f948-7eda-46fa-a5cc-4449c9c18fd5": null, // "LMA" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "98d055f3-07db-4a1c-bb98-6b17e3593e2c": "c1a3866f-e9df-420b-b7ee-7878465530ea", // "Medical Case Conference" in CaseManager becomes "NSW WC Medical Case Conference" in NotusPoint (fuzzy match 86%)
  "5b0eed4d-a587-47d3-b855-cecd127b608d": null, // "Medical Factual Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e617febc-1c94-49e3-a84b-092994f0dfb5": null, // "Medical Factual Report" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1c18c07d-9dde-4ee8-83d6-658ba17eb862": null, // "Mentoring" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "84212bf1-f26e-4abe-ade1-b75c77d6cc49": null, // "Mentoring Support" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "9db1db30-bda5-4c4a-a403-28c31dedef2e": null, // "Modified Bartel Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "daa6bf7b-95c0-473d-80e0-fb0229e04bc2": null, // "More Good Days Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "84a243d8-1420-4eee-a31c-16b4e48f5553": null, // "More Good Days Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7693a775-cc14-4b6b-a5e2-ef90bb7aef0d": null, // "Multiple Workstation assessments" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6f685589-b674-4a37-89ad-2c3f7ac8aace": "5eb1bdd2-6a6c-49c1-96e7-a2e2a35ccd53", // "NIIS Care Needs Assessment" in CaseManager becomes "NIIS Care Needs Assessment" in NotusPoint
  "9208272c-6953-45f3-8b84-8e8f9acc31ae": "95863ee3-6ce6-4540-8510-1618a61f9c8b", // "NIIS OT Service" in CaseManager becomes "NIIS OT Service" in NotusPoint
  "23285a54-3d28-4332-ab9c-257e37f35d68": "5aabfb55-9566-46eb-acff-6f3488d7e35c", // "NIIS Participant Needs Assessment" in CaseManager becomes "NIIS Participant Needs Assessment" in NotusPoint
  "0cc2dd85-268e-4758-bd2e-44f207e528a3": "f5c1e466-ca64-47c2-93f5-a6c49a0fdf4f", // "NIIS PNAR Assessment" in CaseManager becomes "NIIS PNAR Assessment" in NotusPoint
  "5549108b-8359-4f9e-a21d-0364ab23aac8": null, // "Non Comp Rehabilitation Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "f4d27d93-ab88-452a-978d-4399221551ab": null, // "Non Comp Rehabilitation Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ac7e8c25-48ad-43bd-a937-361cf8dd08d0": null, // "Non Comp- In person" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "fa1c8f62-4684-4893-a419-13f09b2d0dd2": null, // "Non Comp- Virtual" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "bfb3b163-50ea-4b49-8474-5485d2ad871a": "9f5b14cf-a41d-4e00-9580-1ae67106e23c", // "NSW WC Activities of Daily Living Assessment" in CaseManager becomes "NSW WC Activities of Daily Living Assessment" in NotusPoint
  "7a84b208-7cd8-429f-af1b-e4967989ee0d": "bfcb85f0-e6e8-468f-8bdd-d70ef0d2128e", // "NSW WC Care Needs Assessment" in CaseManager becomes "NSW WC Care Needs Assessment" in NotusPoint
  "299e4bb7-a352-45e3-8b51-327bb39c5c2e": "2d5377d0-c387-478c-a712-2dd9cbf6c275", // "NSW WC Case Management" in CaseManager becomes "NSW WC Case Management" in NotusPoint
  "2ca0809b-d8b1-420a-bc28-3d1e48d60daa": "515e1870-dfc2-4530-bb8e-4f674c35d6cd", // "NSW WC Ergonomic Assessment" in CaseManager becomes "NSW WC Ergonomic Assessment" in NotusPoint
  "48bc649e-94f9-4ba3-9a09-6310e084ee9c": "17fab9fe-35a4-4f6a-b98e-8e44212e3ec0", // "NSW WC Functional Capacity Assessment" in CaseManager becomes "NSW WC Functional Capacity Assessment" in NotusPoint
  "273a2b4b-996d-46cf-9a7c-bef83a4c3bde": "87bc3ada-957d-4f9a-ba47-544fab57aab0", // "NSW WC Initial Needs Assessment" in CaseManager becomes "NSW WC Initial Needs Assessment" in NotusPoint
  "2c353ee4-9334-4ba1-98dc-0e6f3b86eea6": "e6cda687-e52f-40a8-8511-2905ad3a8ae2", // "NSW WC Labour Market Analysis" in CaseManager becomes "NSW WC Labour Market Analysis" in NotusPoint
  "aa13856a-8d16-4230-8dad-41fa2deec2b9": "c1a3866f-e9df-420b-b7ee-7878465530ea", // "NSW WC Medical Case Conference" in CaseManager becomes "NSW WC Medical Case Conference" in NotusPoint
  "99315cd6-7960-4c35-868b-ad89a13cbdd6": "3a0ec37a-b6a2-4563-9cdf-c763d4ea60f2", // "NSW WC New Employer Services" in CaseManager becomes "NSW WC New Employer Services" in NotusPoint
  "b18e07d9-d2ff-4aac-8676-cec9580bc1e1": "030cc53b-91c6-4bff-9575-0bb872d21ea3", // "NSW WC OT Assessment" in CaseManager becomes "NSW WC OT Assessment" in NotusPoint
  "d1fd5ef7-f0b1-4a33-acbb-54a47a02f931": "02528a1b-12f7-4531-b53d-2b5534c2df3a", // "NSW WC Same Employer Services" in CaseManager becomes "NSW WC Same Employer Services" in NotusPoint
  "2b4559b3-0750-4ba6-8c72-635c9c993cec": "0d369331-8a5b-46be-97a5-430bf0eea7a9", // "NSW WC Voc Rehab Assessment" in CaseManager becomes "NSW WC Voc Rehab Assessment" in NotusPoint
  "c7a1f411-8b14-48c2-807d-8c1682822fc8": "51f9ff74-4053-4d9d-a4d5-d90d41400cdf", // "NSW WC Vocational Assessment" in CaseManager becomes "NSW WC Vocational Assessment" in NotusPoint
  "1aa82dbf-a33e-45be-8606-14847f5a2ca8": "347f8f72-a88c-4bef-a8d2-f30443bebb35", // "NSW WC Vocational Counselling" in CaseManager becomes "NSW WC Vocational Counselling" in NotusPoint
  "f19a5f18-9d20-4e3a-a313-e3e7e72fa70a": "8472f060-444b-4a5a-9175-1d3dd3599e75", // "Oncore Activities of Daily Living Assessment" in CaseManager becomes "Oncore Activities of Daily Living Assessment" in NotusPoint
  "2a44bf86-ceb1-490e-8b42-7d78f1e87126": "ddf81621-107b-458b-b45e-d4720b689872", // "Oncore Ergonomic Assessment" in CaseManager becomes "Oncore Ergonomic Assessment" in NotusPoint
  "27484cb8-07cf-45f6-8412-a866ed522ffb": "827a8944-7974-4738-821e-26ab42fe5b82", // "Oncore Functional Capacity Assessment" in CaseManager becomes "Oncore Functional Capacity Assessment" in NotusPoint
  "e297f6a2-6ff9-4227-8caf-6db5657fd227": "80d7a76d-7773-4de0-a3d8-e771fe9dfd16", // "Oncore Initial Needs Assessment" in CaseManager becomes "Oncore Initial Needs Assessment" in NotusPoint
  "e144c066-1c1d-475b-933e-21bc6cebd97b": "fe33d2dd-960b-4d7f-b320-fe825197e4ea", // "Oncore RTW/Case Management" in CaseManager becomes "Oncore RTW/Case Management" in NotusPoint
  "ce23188e-400a-4926-86a9-7c69b537de5d": "3e6997ca-f077-448b-b94d-815036a17a49", // "Oncore Vocational Assessment" in CaseManager becomes "Oncore Vocational Assessment" in NotusPoint
  "fe6cb873-fa9f-40a2-bcfd-11f060cc77e7": "98fda786-b116-4f28-aa43-33d1628074a9", // "ORAMS Comp Rehabilitation Assessment - S36 - Combined - In Person" in CaseManager becomes "ORAMS Comp Rehabilitation Assessment - S36 - Combined - In Person" in NotusPoint
  "5c46ecb7-6bdb-4abc-9bab-7e9e85aee5ec": "1adf0951-2977-4080-b014-9c496b10aa1d", // "ORAMS Comp Rehabilitation Assessment - S36 - Combined - Virtual" in CaseManager becomes "ORAMS Comp Rehabilitation Assessment - S36 - Combined - Virtual" in NotusPoint
  "92fe9434-2c62-432f-b01c-77d664f60bf3": "a2ff4f2e-e6af-4a07-9afe-09f4437d5ce5", // "ORAMS Comp Rehabilitation Assessment - S36 - Physical - In Person" in CaseManager becomes "ORAMS Comp Rehabilitation Assessment - S36 - Physical - In Person" in NotusPoint
  "49bd4aea-7253-433d-b284-5565487f27e9": "9c379643-eee5-40bc-aef5-fe8a3250d74b", // "ORAMS Comp Rehabilitation Assessment - S36 - Physical - Virtual" in CaseManager becomes "ORAMS Comp Rehabilitation Assessment - S36 - Physical - Virtual" in NotusPoint
  "cc3739c9-5272-46e6-841d-c6dec58d490c": "ea500dd3-61d0-408a-bc49-3172c5415a77", // "ORAMS Comp Rehabilitation Assessment - S36 - Psychological - In Person" in CaseManager becomes "ORAMS Comp Rehabilitation Assessment - S36 - Psychological - In Person" in NotusPoint
  "593eb795-7dde-4b85-b904-09991e8a1964": "abbde19f-d2be-433e-ba72-4582fc129341", // "ORAMS Comp Rehabilitation Assessment - S36 - Psychological - Virtual" in CaseManager becomes "ORAMS Comp Rehabilitation Assessment - S36 - Psychological - Virtual" in NotusPoint
  "2104083a-4e0b-4236-af00-26a51be57f10": "410aa595-e91b-4af7-8c04-299a66f3a223", // "ORAMS Comp Rehabilitation Program - S37 - In Person" in CaseManager becomes "ORAMS Comp Rehabilitation Program - S37 - In Person" in NotusPoint
  "9ad43193-937c-44a3-98d3-b25730787a6d": "0800c508-2b17-4529-a2ba-8c3b5692ee01", // "ORAMS Comp Rehabilitation Program - S37 - Virtual" in CaseManager becomes "ORAMS Comp Rehabilitation Program - S37 - Virtual" in NotusPoint
  "16d6b15e-a756-4828-a6c0-b0831a6eb4d3": "02a441c6-f053-40a0-966b-1f3a1d806fbb", // "ORAMS Ergonomic Evaluation - Brief follow up" in CaseManager becomes "ORAMS Ergonomic Evaluation - Brief follow up" in NotusPoint
  "ae313b2a-b022-450e-aab5-67b27d9fba08": "c26917cb-87b0-4039-ae73-535b96c5bad3", // "ORAMS Ergonomic Evaluation - Comprehensive" in CaseManager becomes "ORAMS Ergonomic Evaluation - Comprehensive" in NotusPoint
  "7b9355b5-c05b-42c8-9cae-e7c59dbc005c": "106e0dc4-61f4-4691-86ae-ab41635c5ff2", // "ORAMS Functional Capacity Evaluation" in CaseManager becomes "ORAMS Functional Capacity Evaluation" in NotusPoint
  "8e702507-0f45-4277-8b8e-3e49cc5245dc": "18ef71d2-4e4d-4142-abaf-b6962d2e5d24", // "ORAMS Non Comp Rehabilitation Assessment - Combined - In Person" in CaseManager becomes "ORAMS Non Comp Rehabilitation Assessment - Combined - In Person" in NotusPoint
  "06eeed1f-001f-403a-9eee-42a3a8646094": "70ed802c-fb89-44a4-897b-ee68ce544e42", // "ORAMS Non Comp Rehabilitation Assessment - Combined - Virtual" in CaseManager becomes "ORAMS Non Comp Rehabilitation Assessment - Combined - Virtual" in NotusPoint
  "f1605bb8-787f-453a-8d2b-3a4fa868217e": "448adc9d-a68c-4fda-89da-61f9b88076be", // "ORAMS Non Comp Rehabilitation Assessment - Physical - In Person" in CaseManager becomes "ORAMS Non Comp Rehabilitation Assessment - Physical - In Person" in NotusPoint
  "17a4c699-c9cb-41c5-b91a-f5639047bb38": "a9a5a461-1dd7-4c2b-9090-cf758221b85d", // "ORAMS Non Comp Rehabilitation Assessment - Physical - Virtual" in CaseManager becomes "ORAMS Non Comp Rehabilitation Assessment - Physical - Virtual" in NotusPoint
  "0a3881da-1aee-450b-a496-93e4265718a0": "98ca6608-3423-4e65-90a2-04ed45a45337", // "ORAMS Non Comp Rehabilitation Assessment - Psychological - In Person" in CaseManager becomes "ORAMS Non Comp Rehabilitation Assessment - Psychological - In Person" in NotusPoint
  "3b0cd439-969d-43f8-ac1b-163c019ca4f1": "a4ecc053-82f9-4e47-8aee-ef7a2fb6b180", // "ORAMS Non Comp Rehabilitation Assessment - Psychological - Virtual" in CaseManager becomes "ORAMS Non Comp Rehabilitation Assessment - Psychological - Virtual" in NotusPoint
  "f6a7814e-0df7-4b9b-a46c-7b5b2d88eb1a": "3c63b488-1e6a-43d7-b10b-48b3238a6181", // "ORAMS Non Comp Rehabilitation Program - In Person" in CaseManager becomes "ORAMS Non Comp Rehabilitation Program - In Person" in NotusPoint
  "dd6c0cf3-ab67-45d2-ba02-f380b8c4b08c": "d233ee53-a87b-4e02-94fd-a9ca78753ef1", // "ORAMS Non Comp Rehabilitation Program - Virtual" in CaseManager becomes "ORAMS Non Comp Rehabilitation Program - Virtual" in NotusPoint
  "cde20043-8dad-4871-a3de-fadb7939ad4b": "fb6aeb35-45e2-4f72-85da-2c590ea04da5", // "ORAMS Offsite Assessment" in CaseManager becomes "ORAMS Offsite Assessment" in NotusPoint
  "f1036b10-9987-40a7-916e-3b91c041a4de": "5807f8a8-010d-4046-955a-3275ee4440ec", // "ORAMS Supplementary Report or Review" in CaseManager becomes "ORAMS Supplementary Report or Review" in NotusPoint
  "ad1f8457-e796-4659-ac6e-dba5a6978902": "7dee9c31-4ec7-4b02-83d5-24b309887297", // "ORAMS Vocational Assessment" in CaseManager becomes "ORAMS Vocational Assessment" in NotusPoint
  "ec214a5e-961f-4f3e-ac58-fedb65d656d9": "e1081a73-145a-4f0a-aaa5-c00439dafc87", // "ORAMS Work Capacity Assessment" in CaseManager becomes "ORAMS Work Capacity Assessment" in NotusPoint
  "fd337307-08a3-4975-81c8-3aa03dbde466": null, // "Other" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "b910f132-482d-492a-8627-71e748dfe96a": null, // "Other" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d8677cdd-3c22-428e-a464-3efe75c6818c": null, // "Pain Management Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c60c2ddb-627f-42c7-9bd4-f0c51e96ba64": null, // "Physical Condition" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2c77913a-64ed-4c8e-b706-011de33a3497": null, // "Pivotl – Business Gap Analysis" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5267f1d7-a627-4e1c-b777-9b0aa251aea7": null, // "Pivotl Module A" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "29e23b77-78b1-42b0-af4a-d44eb09a91a5": null, // "Pre-Vocational Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4de7cfea-17d2-4e5b-b052-b88e8d7974fc": null, // "Prognosis Request" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3062a79c-2f48-45da-bdc6-c25aa145b3f4": null, // "program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "81ee2d3b-7c00-4e28-a871-34351c202eca": null, // "program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1916f00f-342e-47f8-94ac-6aec6f2ebdfc": null, // "program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "da1a8d33-22c7-4249-b744-664b4e3d291a": null, // "Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "7f77aceb-55ba-411e-960c-99db8b5a2837": null, // "Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "91480e99-bbbf-4f4c-b8c7-848c25c72f36": null, // "Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8320605d-6371-4492-9f4a-e5f3a7660c27": null, // "Psychosocial Recovery Readiness Pilot" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "873b994f-b20a-462d-866d-d9cdf6d3b845": null, // "Referral Cancelled" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "055d4709-456b-475c-86a7-080de67c9191": null, // "Rehab Opinion" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5829ef2e-ed7e-4204-92c9-83091c6c1a43": null, // "Report" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1860580d-d711-40fc-a741-47d8f6b1895d": null, // "Report" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "16bbc2b4-e2db-4490-b117-0f03c552bd0f": null, // "Report Only" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e3231e3d-eb0c-449d-8d82-6aad23162dce": null, // "Resume Development" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1091dae9-4b07-4ce7-a0b0-39b6460a22f4": null, // "Ret" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ad4d81b7-30ed-460e-9a59-ccda322c7fc4": null, // "Ret" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "658ee72d-a89a-4342-9a8b-425acf9e6993": null, // "Return to Study" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "843d536c-ae13-4a76-8750-3aab1f89cbd4": null, // "Return to Work" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c74539ad-da17-4548-8cf7-228b992626ad": null, // "Return to Work" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "22adf633-2aa4-47e4-8b6f-4bb0e1ddecb9": null, // "Return to work assistance" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "cd252fee-fd03-4f6a-b6c5-4c158dcf13e5": null, // "Return to work graded plan" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "92793619-5f6d-407a-a45f-4c702d676d18": null, // "Return to work services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3d0d9a2a-9d9b-4aca-9c01-0b8a153de17e": null, // "Review" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "57a93c58-60fc-41cc-8935-182d181f3452": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "a24c3400-fc63-4fb1-a95e-d4bdb72665f7": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "645f7a53-3c6a-4e08-ac59-b2feced34e86": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e35f7e4a-a0a3-427b-8cd8-7c198daf9c90": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e4973ba1-aa3a-4a7c-8efc-5d85615153bc": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c7016490-e7a6-4e07-805b-9e486b24cf1f": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "daf1b12f-47bf-4caf-a4e3-b914d78865b9": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4f4ae9c9-07e9-41d7-8d69-07e6aebbb0af": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "77c3d1e6-93d3-492d-b8d1-13d434de315b": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "469a9dc2-2a29-4ecd-bc41-e78d09ac793b": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6dfba2e0-ed72-4c3f-9f49-101d56478371": null, // "RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d02cb304-d37b-4ccf-af11-6228628923df": "fe33d2dd-960b-4d7f-b320-fe825197e4ea", // "RTW - Case Management" in CaseManager becomes "Oncore RTW/Case Management" in NotusPoint (fuzzy match 88%)
  "a3948d80-de3e-44d2-913b-eebdc8ed814d": null, // "RTW - Host" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "718de6ae-06cb-4aab-8344-8e76d4f91ee2": null, // "RTW - New Employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1a8710c1-769e-4cd4-a44f-b845d40455d6": null, // "RTW - New Employer - Host" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e43b96ff-8fe8-46a4-a0eb-a5c35a6d5adc": null, // "RTW - New Employer/Host" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e63b85f7-6328-415f-a60c-b6c6696a9f43": null, // "RTW - Pre- Disability Employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d85a1d1f-9a1d-4c17-8fe5-17d6dbae6fda": null, // "RTW - same employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "84807443-950b-4e00-a484-93a5b12cfed8": null, // "RTW - Transition to New Employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6a8b12d4-7ae0-40bc-a8f9-2a7b4d19a570": "fe33d2dd-960b-4d7f-b320-fe825197e4ea", // "RTW -Case Management" in CaseManager becomes "Oncore RTW/Case Management" in NotusPoint (fuzzy match 88%)
  "b5958b2d-3dd9-4dda-959a-cadda5c606df": "fe33d2dd-960b-4d7f-b320-fe825197e4ea", // "RTW Case Management" in CaseManager becomes "Oncore RTW/Case Management" in NotusPoint (fuzzy match 88%)
  "a4e8e5a4-b174-43f4-96c2-746a38fbb9fa": null, // "RTW facilitation" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3f76ab7f-8106-4dea-8b33-61a480324ae8": null, // "RTW new employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "f6b98444-24f1-42cd-8cf6-31c7d34acf1d": null, // "RTW planning" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "09be9aef-b9f3-4c92-90be-f17dd2c0c8e7": null, // "RTW Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e7eb0ca8-e4ac-46df-a015-78db653d0a26": null, // "RTW Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2f42e778-b16b-4434-99d2-332d88e04514": null, // "RTW Same Employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "d59a06fb-fc1d-4e97-a31c-c1668b56871b": null, // "RTW Same employer" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "af8aaa42-f8ad-4991-89c1-ca7a6a7372ac": null, // "RTW Same employer - HOST" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "9cdf4f4f-b05c-4729-8c57-642f807bc0dd": "83cb6b32-4eb7-47e2-8b80-c73ef2e5baa6", // "RTW Services" in CaseManager becomes "Self Insured WCQ RTW Services" in NotusPoint (fuzzy match 84%)
  "0670922c-b8f9-4fb9-85c4-c230be67810b": "83cb6b32-4eb7-47e2-8b80-c73ef2e5baa6", // "RTW Services" in CaseManager becomes "Self Insured WCQ RTW Services" in NotusPoint (fuzzy match 84%)
  "dd17235d-4c63-4a45-840e-48238e135814": null, // "RTW Support" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "682b4458-f251-4099-b6d8-9a96bbffdade": null, // "S36 Rehab Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "0b6bad1b-c85c-46e6-a5e0-909941561d06": null, // "S37 Rehab Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "584fbcc2-49a3-4aac-8854-e499845339d3": null, // "Section 36" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "f7599892-3b0b-4704-95bd-9b80e9472a4a": null, // "Section 37" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4b051243-8798-42d1-997a-e86326e06d65": null, // "Section 40 Ax" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "aff15615-7858-4879-8af4-4ad62213099b": "3e46d284-5a5c-401f-b58f-42c7a23bb3ec", // "Self Insured WCQ Common Law" in CaseManager becomes "Self Insured WCQ Common Law" in NotusPoint
  "3fdc938d-db1e-431c-84f2-60aaedb4107a": "a78a1904-f58c-4739-9624-5a040e82de00", // "Self Insured WCQ Graduated Return to Work Program" in CaseManager becomes "Self Insured WCQ Graduated Return to Work Program" in NotusPoint
  "4bdd906d-d776-4668-8025-0a9b684bc98b": "3ab95bdc-4edf-41b0-b4c5-db7006fe160f", // "Self Insured WCQ Initial Job Seeking Skills Assessment" in CaseManager becomes "Self Insured WCQ Initial Job Seeking Skills Assessment" in NotusPoint
  "27c35d32-1005-4ecc-8591-a922bf84d293": "24443ff8-3f20-4b5c-8c89-c9500a89de41", // "Self Insured WCQ Initial Needs Assessment" in CaseManager becomes "Self Insured WCQ Initial Needs Assessment" in NotusPoint
  "42b0a315-0b56-4fd0-bf2e-6de1369c283b": "d2f378a5-7869-465a-8fe3-13a6c45b4536", // "Self Insured WCQ Job Placement Services" in CaseManager becomes "Self Insured WCQ Job Placement Services" in NotusPoint
  "7e4f33c0-be78-4ccc-b75d-4875fff00410": "619d4689-e9fe-4999-92b9-a3da55322232", // "Self Insured WCQ Job Preparation Services" in CaseManager becomes "Self Insured WCQ Job Preparation Services" in NotusPoint
  "7fba5421-6a45-4517-96c6-1046f5f157e6": "73afad02-2f9a-4cd0-8f81-918c675a3b80", // "Self Insured WCQ Job Seeking Assistance" in CaseManager becomes "Self Insured WCQ Job Seeking Assistance" in NotusPoint
  "18d0e72b-5b2c-4136-8201-6ab07b6cdf04": "a11843a7-4ec5-435e-8759-2780ee9cbe6a", // "Self Insured WCQ Job Seeking Skills Assessment" in CaseManager becomes "Self Insured WCQ Job Seeking Skills Assessment" in NotusPoint
  "11e71e66-1432-47c8-897a-f0b59af5e814": "83cb6b32-4eb7-47e2-8b80-c73ef2e5baa6", // "Self Insured WCQ RTW Services" in CaseManager becomes "Self Insured WCQ RTW Services" in NotusPoint
  "8eade486-ce48-4c36-98a8-33bf009b02da": "56e49600-f206-46e0-8c90-76e8257cd9b4", // "Self Insured WCQ Vocational Assessment" in CaseManager becomes "Self Insured WCQ Vocational Assessment" in NotusPoint
  "5b35d5ab-627a-48eb-8dc6-ee8c6d1966db": null, // "Serious Injury" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2cb00b80-9ee9-4558-baa0-a8271b1670a3": null, // "SFE Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c428a1fe-3040-4303-b526-f51545dbbb29": null, // "SFE Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "b051d367-445e-4fa9-8593-b0762b178b7d": null, // "SNA Ax" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ea49ba83-1d27-4025-82cb-930315e1df64": null, // "Social Support" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "97f85bc8-99af-4b4a-9991-ebb2d5e686d9": null, // "Social Work" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ed31e627-62be-4438-84c5-2890bfca02ef": null, // "Social Work" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6609fa5c-6740-45e5-8a54-80bb248fd633": null, // "Social Work Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e8e37de2-b1ad-4557-8f6e-a83fe58e70ad": null, // "Social Work Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3729f7a5-46eb-4aa7-bb4f-f91f48dc6981": null, // "Social Work Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "c6d74bf4-f3b1-45ee-80ce-fa6ac6994caf": null, // "Social Work Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "3adc4fdb-0bd0-44e6-ae89-d36da5c262d7": null, // "Suitable Duties Plan / Workplace Evaluation and Assessment / Functional Capacity Evaluation and report / Monitoring Suitable Duties / Workplace Facilitated Discussion" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "77ec1dbd-79ea-4468-8d41-6376eded4cc0": null, // "Telehealth" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6e7bb59d-d007-474e-9f7b-54a7526b43b1": null, // "Telehealth" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8e78173d-e320-4ffb-b7d9-7a24d34148a7": null, // "Telehealth - RTW" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8a2ef670-0940-4021-b30c-a425251bae13": null, // "Tier 1" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8c827e7d-5344-497b-be9d-ab18cb24ac25": null, // "Tier 2" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e78b88a7-fffe-47fb-a401-75d8dcdf75a4": null, // "Tier 3" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "b145c9df-9349-48fd-980c-aaac1e39bf21": null, // "TPD" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4404f4da-5a47-4ec2-aee1-bb3209cdb503": null, // "TPD Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "6ff09f6b-8061-4baa-86d2-365b22099a7e": null, // "TPD Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5e8701ff-3756-4890-bbc0-f06bc9ee28ab": null, // "TPD Assist" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "0715c471-cb80-4298-8bf6-3ef749547fcf": null, // "training" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "af6618ee-dfea-4390-a663-e326889e223f": "c75304eb-9e74-4762-a1c5-8c956096071d", // "Transferrable Skills Assessment" in CaseManager becomes "LI Transferrable Skills Assessment" in NotusPoint (fuzzy match 91%)
  "ec1acf2c-f93c-4562-bd73-d6403eab5e18": null, // "TSA/LMA" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "4e7c2a43-699d-4439-954f-0543e090a9b2": null, // "Vehicle Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8c21648f-f082-4f23-8a3c-3b44672ce1ec": null, // "Veteran Payment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1077ecb1-896c-4850-ae9d-9733556bbbb4": null, // "Voc Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "fb27c1cc-4889-4c85-9423-6c55acd8fe81": null, // "Voc Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1d885378-ef12-49e5-bed8-d11aa0c8832e": null, // "Voc Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "ab12afbe-5803-4a12-ab96-e0f9be15902c": null, // "Voc Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e2ef4642-7bce-470b-a347-f1fe31bb45c1": null, // "Voc Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "a4cf22d9-0520-4775-9ff2-bcf7fe68f805": null, // "Voc Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "78db6654-1ca8-4b7d-b7e8-1577949b2477": null, // "Vocational Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "08647d73-8410-410c-9c7e-6d4ce0df9045": null, // "Vocational Assistance" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "218e497d-f187-447c-8844-a03067bb88d4": null, // "Vocational Counselling" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "2ae3c185-c1bf-4fdc-a529-60f602bf0ba0": null, // "Vocational Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1bd5b9f5-9ef1-42d3-8158-b3e65e6e4566": "e8fb5977-5fb5-4a10-ac54-1545edd8357b", // "WC NT Activities of Daily Living Assessment" in CaseManager becomes "WC NT Activities of Daily Living Assessment" in NotusPoint
  "c2183100-918d-435d-be5a-705318155f36": "c1c3d7df-3283-4ec2-a2a8-fa9dd4adc5c4", // "WC NT Ergonomic Assessment" in CaseManager becomes "WC NT Ergonomic Assessment" in NotusPoint
  "31720bb7-a642-47cf-b3a9-5732904af48a": "40f7063f-6cd1-451b-9cdd-270a5ee1d60c", // "WC NT Functional Capacity Assessment" in CaseManager becomes "WC NT Functional Capacity Assessment" in NotusPoint
  "5d9036eb-6072-4852-ba7c-2fae72ad09f0": "64c9f0e5-23e3-4829-a96a-58d33add3a28", // "WC NT Initial Needs Assessment" in CaseManager becomes "WC NT Initial Needs Assessment" in NotusPoint
  "166a797a-5e85-4e46-a350-a9043e294f12": "0d9a219e-9bd7-41fe-9778-6c197d926f65", // "WC NT Labour Market Analysis" in CaseManager becomes "WC NT Labour Market Analysis" in NotusPoint
  "d5be9d89-4b0a-48db-9729-e6e4f0525718": "6e2317dc-fa4f-4256-b6d4-c7ac64eb9809", // "WC NT New Employer Services" in CaseManager becomes "WC NT New Employer Services" in NotusPoint
  "ce1bbeb9-4564-497c-8029-47cdf07de233": "bfcec09f-4e76-478a-a3bf-66b595e8998c", // "WC NT Same Employer Services" in CaseManager becomes "WC NT Same Employer Services" in NotusPoint
  "0b433b37-ccc7-43e2-b325-5291fc8c66c0": "20fc6697-289c-4d0f-bc56-5b0ec2dd7adc", // "WC NT Vocational Assessment" in CaseManager becomes "WC NT Vocational Assessment" in NotusPoint
  "344c4398-bc26-4c47-b433-0f958ac9448a": "f59d660b-11d3-4580-afa9-ea7d25cd50b7", // "WC QLD Activities of Daily Living Assessment" in CaseManager becomes "WC QLD Activities of Daily Living Assessment" in NotusPoint
  "e3855801-dbda-4c77-8a40-1789fb1e6689": "199244ce-264b-49ea-801d-2f0437325050", // "WC QLD Driving Assessment" in CaseManager becomes "WC QLD Driving Assessment" in NotusPoint
  "22c2f850-8610-4ebf-9d85-4063e063df46": "31732669-9816-4b28-9c51-ae13da4aa166", // "WC QLD Employment Connect" in CaseManager becomes "WC QLD Employment Connect" in NotusPoint
  "e5ab6be8-ea7f-4017-9566-afd8f7c09467": "c9816efd-e1b3-40e5-9cf8-2ac4659853b8", // "WC QLD Functional Capacity Assessment" in CaseManager becomes "WC QLD Functional Capacity Assessment" in NotusPoint
  "9cf68669-64bf-4fdc-a9ec-e53eae4a0e5c": "0ab4413a-ff5b-462c-aefe-81f62d1ef144", // "WC QLD Gratuitous Care Assessment" in CaseManager becomes "WC QLD Gratuitous Care Assessment" in NotusPoint
  "6f37d949-cb93-49d6-8d9b-c85136a0a48a": "9d7cb532-c4bd-4736-b703-5969dc4e8e29", // "WC QLD Home Modifications Assessment" in CaseManager becomes "WC QLD Home Modifications Assessment" in NotusPoint
  "91785a75-bbd0-468a-948f-9b2b4d53492b": "da7c012a-2b6e-4bff-a097-442b2e0431f7", // "WC QLD Host Employer Placement" in CaseManager becomes "WC QLD Host Employer Placement" in NotusPoint
  "115ea244-221c-4b29-a501-ad071dd1e519": "7990720f-5b7c-4734-848a-0af6eb8e096b", // "WC QLD Initial Needs Assessment" in CaseManager becomes "WC QLD Initial Needs Assessment" in NotusPoint
  "d683be45-871e-4923-a06a-55a12249e836": "facda3ca-aa3e-4177-81b4-7512b0386929", // "WC QLD Job Placement Services - New Employer" in CaseManager becomes "WC QLD Job Placement Services - New Employer" in NotusPoint
  "294c38f0-c935-4ba9-8b33-7f1c0a210b9f": "1fcfe239-a2af-4e75-86c5-8805e6eca355", // "WC QLD Job Placement Services - Work Hardening Program" in CaseManager becomes "WC QLD Job Placement Services - Work Hardening Program" in NotusPoint
  "d2ee358a-f8d2-4438-9c8d-b5c399aa124d": "4d2fcde0-a446-4c56-9131-19c37dab9bd6", // "WC QLD Job Seeking Skills Assessment" in CaseManager becomes "WC QLD Job Seeking Skills Assessment" in NotusPoint
  "9c17d995-cd7a-4a17-8053-c03aa6716774": "127a84a1-d9f8-4d4a-8fc2-866b0fdfe927", // "WC QLD MBI Assessment" in CaseManager becomes "WC QLD MBI Assessment" in NotusPoint
  "cf0e7a0a-ee05-4174-9275-f97ce6973aea": "fe29f4cc-d3e5-46c6-a969-b5f7c28002d2", // "WC QLD Mediation Services" in CaseManager becomes "WC QLD Mediation Services" in NotusPoint
  "0ce17fdf-bbe8-427e-a920-77b236abefee": "d829eaff-b10c-4916-a92a-5195ab4f2602", // "WC QLD Monitoring Suitable Duties" in CaseManager becomes "WC QLD Monitoring Suitable Duties" in NotusPoint
  "76c8d761-16ad-4607-a98b-008f5d4ea8ea": "59b997ce-51d9-4726-8e6f-1c36166e4e5f", // "WC QLD Return to Work Facilitation" in CaseManager becomes "WC QLD Return to Work Facilitation" in NotusPoint
  "83b30792-86da-4091-8f54-ab229aa5e29d": "8077077b-bf46-44ec-af0d-ced3bd04d19c", // "WC QLD Suitable Duties Plan" in CaseManager becomes "WC QLD Suitable Duties Plan" in NotusPoint
  "c18112d9-f1b8-4cf7-89af-d0a634a33e22": "a07aa0d9-31d2-4012-853d-8d11dc020d7e", // "WC QLD Vocational Assessment/TSA" in CaseManager becomes "WC QLD Vocational Assessment/TSA" in NotusPoint
  "a113f0b5-c084-4f63-bdc7-7ef03846fa41": "1de72442-4ace-4f4e-8d38-5b9313a636d4", // "WC QLD Workplace Evaluation" in CaseManager becomes "WC QLD Workplace Evaluation" in NotusPoint
  "a17225db-28a5-4302-9be5-46a451b08933": "e197773b-5570-4fcc-80ae-58adf97979f3", // "WC QLD Workplace Facilitates Discussions" in CaseManager becomes "WC QLD Workplace Facilitates Discussions" in NotusPoint
  "f83140d0-a22a-4f3c-880a-e22d5be0aac4": "44f056e8-2bc6-4dbc-bd20-996b9c0e6c42", // "WC WA Aids and Appliances" in CaseManager becomes "WC WA Aids and Appliances" in NotusPoint
  "2e9d4897-5590-47ca-95a5-2de5d73d4c74": "51c184e5-dc26-40e8-875b-717dbeff962e", // "WC WA Ergonomic Assessment" in CaseManager becomes "WC WA Ergonomic Assessment" in NotusPoint
  "0127ab3c-088c-4111-9078-069b824cd8ae": "1b45ef70-d5db-4749-8400-dd71cf8a03b8", // "WC WA Functional Capacity Assessment" in CaseManager becomes "WC WA Functional Capacity Assessment" in NotusPoint
  "ab204f3b-bd7f-40f9-a29a-e5692de0ee7a": "d5777743-2290-442d-91d5-adb9039a230f", // "WC WA Job Demands Assessment" in CaseManager becomes "WC WA Job Demands Assessment" in NotusPoint
  "111c5c05-4f73-415f-bf53-1387458b64b8": "b2925b36-1e67-4c1a-90df-ab962b14f34a", // "WC WA Rehabilitation Program - New Employer" in CaseManager becomes "WC WA Rehabilitation Program - New Employer" in NotusPoint
  "cef00a0b-a7ed-4688-8e36-13690807756b": "b22f4337-dc9c-4386-9cc5-a4c9acd577f3", // "WC WA Rehabilitation Program - Same Employer" in CaseManager becomes "WC WA Rehabilitation Program - Same Employer" in NotusPoint
  "0a34bbd6-d558-4025-976a-3c582cb61468": "e8b2d166-6e20-40d4-9d61-eac3fc9583e6", // "WC WA Vocational Assessment" in CaseManager becomes "WC WA Vocational Assessment" in NotusPoint
  "03d6644c-74cf-4049-a481-c55075ae9d4e": "4682774b-3e3b-4702-bd3b-a395f09bc98e", // "WC WA Workplace Assessment" in CaseManager becomes "WC WA Workplace Assessment" in NotusPoint
  "d304571f-4718-4565-991c-efb797907fb2": null, // "Wellbeing Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "1d98ed17-9b71-4b2f-a2fd-0cc848ab86ab": null, // "Wellness Program" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "968b5659-313d-463a-a303-e0f48de46d95": null, // "Work Readiness" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "8d6065f2-57fc-48ab-91ed-61af1c4ab4d5": null, // "work readiness" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "5ca3a3fc-51e2-40b9-a573-5671f601b1fd": null, // "Workplace Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "e96c89ab-2b60-46f6-b5d9-14bbd9883ba8": null, // "Workplace Health & Safety Assessment" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "976a117c-049e-4543-a60a-f24287f12d2e": null, // "Worksite Assessment & medical factual" in CaseManager becomes "Unmatched Requirements" in NotusPoint
  "35448e2d-e141-4a0b-95b5-c6d0c8f068a6": null, // "Worksite Assessment & RTW Services" in CaseManager becomes "Unmatched Requirements" in NotusPoint
};

// Used when a CM case has no Referral Type selected.
Object.defineProperty(requirementMapping, 'UNMATCHED_REQUIREMENT_ID', { value: "ce5f41d4-12ce-4f86-b3a9-6502bb898e60" });

module.exports = requirementMapping;
